/*
 * This source file was generated by the Gradle 'init' task
 */
package com.isi.desa;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
